### ISSUE TITLE
api모델은 어떻게 만드는 겁니까?

### ISSUE THREAD

**Issue by ggokka** [krazure/hybrid-aks-hol#1]
핸즈온 매뉴얼에 보면 apimodel 이나 iis.yml 등의 구성요소나 서비스들의 설정을 담고있는 중요한 파일들이 존재하고 이 파일들이 절대적인 역할을 합니다.

실전에서 이 파일들은 손으로 만드는 건가요? 아니면 애저의 유틸리티 툴로 지원되는 내용입니까?

**Comment by ggokka** [comment]
ARM템플릿은 VS에서 만들수 있네요.
https://docs.microsoft.com/ko-kr/azure/azure-resource-manager/vs-azure-tools-resource-groups-deployment-projects-create-deploy

**Comment by rkttu** [comment]
이 핸즈온랩 모듈에서 의도하는 것은 ARM 템플릿을 수동으로 만드는 것이 아닙니다. 어떻게 동작하는지 다시 한 번 설명드리면 다음과 같습니다.

1. 핸즈온랩의 각 단계를 순서대로 진행하는 과정에서, API 모델은 핸즈온랩 모듈에 있는 코드를 복사해서 만듭니다. 텍스트 에디터나 Visual Studio Code를 사용하시면 편리합니다.
2. 새로 만든 API 모델 파일을 파워셸 스크립트로 API 모델을 메모리에 불러옵니다. (이것도 핸즈온랩 모듈 안에 파워셸 코드가 있고, 경로만 정확하게 지정해서 그대로 실행하시면 됩니다.)
3. 파워셸 코드로 필요한 프로퍼티 값을 변경하고, 그것을 다시 완성된 API 모델 파일로 저장합니다. 단, 기존 API 모델 파일을 덮어씌우시면 안되고 별도의 파일 경로로 만들어야 합니다. (이것도 핸즈온랩 모듈 안에 파워셸 코드가 있습니다.)
4. 완성된 API 모델 파일을 파라미터로 지정해서 aks-engine 바이너리로 실행합니다. aks-engine에서 유효성 검사를 거쳐 문제가 없으면 _output 폴더가 만들어지고, **이 안에 단순히 ARM 템플릿만 만들어지는게 아니라 kubeconfig, 인증서 등 각종 주변 파일들이 함께 만들어집니다.**

혹시 핸즈온랩 모듈을 보고 위의 내용이 전달이 안되셨다면 내용을 좀 더 보강해보겠습니다.

고맙습니다. :-)

**Comment by rkttu** [comment]
답변이 된 것으로 보고 이슈는 닫겠습니다. 의견 주셔서 감사합니다. :-)
